version: '3.9'

services:
  pocamarket_api:
    build:
      context: ./pocamarket_api
      dockerfile: Dockerfile
      target: dev
    container_name: pocamarket_api
    ports:
      - "8080:8080"
    volumes:
      - ./pocamarket_api:/src
    networks:
      - pocamarket_network

  pocamarket_web:
    build:
      context: ./pocamarket_web
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./pocamarket_web/:/src
      - /src/node_modules
    env_file:
      - ./pocamarket_web/.env
    depends_on:
      - pocamarket_api
    networks:
      - pocamarket_network

networks:
  pocamarket_network:
    driver: bridge
