version: '3.8'

services:
  pocamarket_api:
    build: ./pocamarket_api
    ports:
      - "8080:8080"
    volumes:
      - ./pocamarket_api:/src
    networks:
      - pocamarket_network

  pocamarket_web:
    build: ./pocamarket_web
    ports:
      - "3000:3000"
    volumes:
      - ./pocamarket_web:/src
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - pocamarket_api
    networks:
      - pocamarket_network

networks:
  pocamarket_network:
    driver: bridge
