version: '3.9'

services:
  pocamarket_api:
    build:
      context: ./pocamarket_api
    container_name: pocamarket_api
    ports:
      - "8080:8080"
    volumes:
      - ./pocamarket_api:/src
    networks:
      - pocamarket_network

  pocamarket_web:
    build:
      context: ./pocamarket_web
    container_name: pocamarket_web
    ports:
      - "3000:3000"
    volumes:
      - ./pocamarket_web:/src
    environment:
      - NEXT_PUBLIC_API_URL=http://pocamarket_api:8080
    networks:
      - pocamarket_network

networks:
  pocamarket_network:
    driver: bridge
